pyra/apps/news/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'apps.news.views.index', name='index'),
    url(r'^(?P<pk>\d+)/(?P<slug>[a-zA-Z0-9_,.-]+)\.html$',
        'apps.news.views.detail', name='detail')
)

pyra/pyra/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'apps.website.views.home', name='home'),
    url(r'^news/', include('apps.news.urls', namespace='news')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

pyra/apps/news/models.py
# -*- encoding: utf-8 -*-
import datetime

from django.db import models
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse

from model_utils import Choices
from model_utils.fields import StatusField
from model_utils.models import TimeStampedModel

from django_extensions.db.fields import AutoSlugField


User = get_user_model()


class News(TimeStampedModel):
    STATUS = Choices('draft', 'published')

    title = models.CharField(u'Tytuł', max_length=256)
    slug = AutoSlugField(populate_from='title')
    date = models.DateTimeField(u'Data publikacji',
                                default=datetime.datetime.now)
    author = models.ForeignKey(User, verbose_name='Autor')
    precontent = models.TextField(u'Zajawka', help_text=u'Wstęp do newsa',
                                  blank=True)
    content = models.TextField(u'Treść', blank=True)
    status = StatusField()

    class Meta:
        verbose_name = 'news'
        verbose_name_plural = 'news'
        ordering = ['-date']
        get_latest_by = 'date'

    def __unicode__(self):
        return self.title

    @classmethod
    def queryset(cls):
        return cls.objects.select_related('user')

    @classmethod
    def get_latest_news(cls):
        return cls.queryset().filter(status=cls.STATUS.published)[0:3]

    def get_absolute_url(self):
        return reverse('news:detail', args=[self.pk, self.slug])

pyra/apps/news/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import (
    get_object_or_404,
    redirect
)

from annoying.decorators import render_to

from .models import News


@render_to('news/index.html')
def index(request):
    return {}


@render_to('news/detail.html')
def detail(request, pk, slug):
    news = get_object_or_404(News, pk=pk)
    if news.get_absolute_url() != request.path_info:
        return redirect(news.get_absolute_url())

    return {
        'news': news
    }

pyra/apps/website/views.py
# -*- encoding: utf-8 -*-
from annoying.decorators import render_to

from apps.news.models import News


@render_to('website/home.html')
def home(request):
    return {
        'news_list': News.get_latest_news()
    }

pyra/apps/news/templates/news/detail.html
{% extends 'website/base.html' %}

{% block content %}
<h1>{{ news }}</h1>
<p>
    <small>
        Opublikowano: {{ news.date }},
        Autor: {{ news.author.get_full_name }}
    </small>
</p>
{{ news.content|safe }}
{% endblock %}

pyra/apps/news/templates/news/index.html
{% extends 'website/base.html' %}

{% block content %}
{% endblock %}

pyra/apps/website/templates/website/base.html
<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Poznań Python Programmers">
        <meta name="author" content="">
        <title>PyRa - Poznań Python Programmers</title>
        <link href="{{ STATIC_URL }}website/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>

        <div class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'home' %}">PYRA</a>
                </div>
                <div class="navbar-collapse collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="">Spotkania</a></li>
                        <li><a href="">Prelegenci</a></li>
                        <li><a href="">Sponsorzy</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container">
        {% block content %}{% endblock %}
            <footer>
                <p class="pull-right"><a href="#">TOP</a></p>
                <p>&copy; {% now 'Y' %} PyRa</p>
            </footer>
        </div>

        <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="{{ STATIC_URL }}website/vendor/bootstrap/js/bootstrap.min.js"></script>
    </body>
</html>

pyra/apps/website/templates/website/home.html
{% extends 'website/base.html' %}

{% block content %}
<h2>Aktualności</h2>
<ul>
{% for news in news_list %}
    <li><a title="{{ news }}" href="{{ news.get_absolute_url }}">{{ news }}</a></li>
{% endfor %}
</ul>
<a href="{% url 'news:index' %}">Archiwum</a>

{% endblock %}